# Generated by Django 5.0.6 on 2024-05-16 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(default='nombre default', max_length=100, verbose_name='Nombre completo')),
                ('sueldo', models.FloatField(default=1000, verbose_name='Sueldo')),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('letra', models.CharField(default='A', max_length=100, verbose_name='Letra')),
                ('maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.maestro')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salones',
            },
        ),
    ]
